### PR TITLE
Removing some images and links absolute paths

### PR DESCRIPTION
**Pull request by ilgrosso**

### CODE REVIEW

**Comment by Humbedooh** [comment]
I'd think that in popup.css, the "../images" should be replaced with "images/" to be correct.
Other than that, looks good!

**Comment by ilgrosso** [comment]
with `images/` images are not found because `popup.css` is under the `css/` folder

**Comment by Humbedooh** [comment]
gotcha, my bad :) I'll merge this.

**Comment by ilgrosso** [comment]
Cool! :-)

**Comment by Humbedooh** [comment]
d'oh, this won't work. my bad!
You committed changes to ponymail.js - this is not the file(s) to edit.
the `site/js/dev/ponymail_*.js` files are the ones that need editing

**Pull request merged**
